import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Disclaimer",
  description:
    "Terms of use and disclaimer for ReportDoctor.pk generated reports, data analysis, payment workflow, and user responsibility."
};

export default function TermsDisclaimerPage() {
  return (
    <>
      <section className="page-hero compact-hero">
        <div>
          <p className="eyebrow">Terms</p>
          <h1>Terms and Disclaimer</h1>
          <p>Last updated: June 16, 2026</p>
        </div>
      </section>
      <section className="section article-body">
        <h2>Informational reports</h2>
        <p>
          Reports generated by ReportDoctor.pk are analytical support. They help users understand uploaded data, but they
          are not financial, legal, tax, medical, accounting, or investment advice.
        </p>
        <h2>User responsibility</h2>
        <p>
          Users are responsible for the accuracy, completeness, and lawful use of uploaded data. Incorrect source files can
          produce incorrect summaries, charts, and recommendations.
        </p>
        <h2>Manual payment MVP</h2>
        <p>
          The launch version supports manual Easypaisa payment and WhatsApp proof verification for local users. International
          checkout is planned. Payment confirmation, bank transfer requests, and refunds should be handled manually until a
          formal payment gateway is integrated.
        </p>
        <h2>No professional advice</h2>
        <p>
          The service does not provide legal, tax, medical, financial, investment, or certified accounting advice. Consult a
          qualified professional where required.
        </p>
        <h2>Availability</h2>
        <p>
          This MVP may be updated, paused, or changed while the product is being developed. Deployment owners should monitor
          logs, file limits, and server costs.
        </p>
      </section>
    </>
  );
}
